travis:
  secure:
    BINSTAR_TOKEN: cONC6Dr7wDqP3MhI3qVfvlQTJabfhrp4uUhQImve29FsAqTguwNxvS9KDv6ui84EW2TjKsJDcKMDTz77cW85zHZ9w1olyN1kt8F5SiVYd0cfINW97g4a/EOEcY05oBIGWdPDIpLpA4pLrtmzeMwy4VAK2p4LqXupBwTzNXQrbQC9b2hwwoo3y2boUHLp6hiL1AiQD1ZQluHFDaoqyNZTIDDpDvSui+q1fsTCaNwux0xCVL9BzIHfjwzW6tyisWZhoKtwh1jdfR++nc27aEZjW3x15l3pIrd58D2XRwdiPbe4l2Kno5eOl3cMDeDhvmEPUCSPaV5cYQjNgZvOluvxwEQmZ6Q3f1aKuQeaciY8Xa2P/vEhEx6RvLgCIoxIk3fde7n+Vg0WMrVyTWaBeWXZA/OzT4GghvitzrU51kkawG1UInOgkD8cj3uKSNrrcIJyhk0VU3N2kUiV3Om0fYtZM6yhrb5DYQJa0+HbHaIZgTp9M/PH5O2sILI9p9VD5JOmlWn+dS0cZ6A6xV7Wj/AOFgllaCrRTqxXwlr9Ycnner2MXgVjuur0oNYkZPARcgvBorRpNpaAEOk0c0SpC/gzc2srY6Lmb38iobUiQN8lhIxtXM4sMr8umShJHln6TkhTS8nuNxgVGTVcnX+cbVB5NFNfGCEaua8bES91SQ9u9/k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
